# =================================================================================================
# Global hotkeys (cannot conflict with other hotkeys)
confirm = ['tab', 'enter']
quit = ['esc', '']
cd_quit = ['q', '']

# movement
list_up = ['up', '']
list_down = ['down', '']
page_up = ['left', '']
page_down = ['right', '']

# file panel control
create_new_file_panel = ['t', '']
close_file_panel = ['w', '']
next_file_panel = ['ctrl+right', '}']
previous_file_panel = ['ctrl+left', '{']
toggle_file_preview_panel = ['f', '']
open_sort_options_menu = ['o', '']
toggle_reverse_sort = ['R', '']

# change focus
focus_on_process_bar = ['P', '']
focus_on_sidebar = ['S', '']
focus_on_metadata = ['M', '']

# create file/directory and rename
file_panel_item_create = ['n', '']
file_panel_item_rename = ['r', '']

# file operations
copy_items = ['c', '']
cut_items = ['m', '']
paste_items = ['v', '']
delete_items = ['ctrl+d', '']
permanently_delete_items = ['d', '']

# compress and extract
extract_file = ['U', '']
compress_file = ['Z', '']

# editor
open_file_with_editor = ['e', '']
open_current_directory_with_editor = ['E', '']

# other
pinned_directory = ['P', '']
toggle_dot_file = ['.', '']
change_panel_mode = ['l', '']
open_help_menu = ['?', '']
open_command_line = [':', '']
open_spf_prompt = ['>', '']
open_zoxide = ['i', '']
copy_path = ['p', '']
copy_present_working_directory = ['g', '']
toggle_footer = ['F', '']

# =================================================================================================
# Typing hotkeys (can conflict with all hotkeys)
confirm_typing = ['tab', 'enter']
cancel_typing = ['esc', 'ctrl+c']

# =================================================================================================
# Normal mode hotkeys (can conflict with other modes, cannot conflict with global hotkeys)
parent_directory = ['shift+tab', 'backspace']
search_bar = ['/', '']

# =================================================================================================
# Select mode hotkeys (can conflict with other modes, cannot conflict with global hotkeys)
file_panel_select_mode_items_select_down = ['shift+down', '']
file_panel_select_mode_items_select_up = ['shift+up', '']
file_panel_select_all_items = ['A', '']
