# we only include settings which differ from the defaults
# https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md

gui:
  scrollHeight: 3
  scrollPastBottom: true
  scrollOffMargin: 4
  tabWidth: 2
  skipAmendWarning: true
  skipDiscardChangeWarning: false
  sidePanelWidth: 0.30
  timeFormat: '2006-01-02'
  shortTimeFormat: 3:04PM
  nerdFontsVersion: '3'
  showDivergenceFromBaseBranch: onlyArrow
  filterMode: fuzzy
  mouseEvents: false
  theme:
    selectedLineBgColor:
      - black

    # Main UI colors
    activeBorderColor:
      - '#ffca58'
      - bold
    inactiveBorderColor:
      - '#858085'
    searchingActiveBorderColor:
      - '#49CAE4'
      - bold
    optionsTextColor:
      - '#49CAE4'
    defaultFgColor:
      - '#FCFCFA'

    # Status colors
    unstagedChangesColor:
      - '#FF7272'
    cherryPickedCommitFgColor:
      - '#49CAE4'
    cherryPickedCommitBgColor:
      - '#A093E2'
    markedBaseCommitFgColor:
      - '#49CAE4'
    markedBaseCommitBgColor:
      - '#FFCA58'

git:
  # See https://github.com/jesseduffield/lazygit/blob/master/docs/Custom_Pagers.md
  paging: # to be changed in (likely) 0.56 to an array `pagers`
    colorArg: always
    pager: 'delta --dark --paging=never --line-numbers --side-by-side --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"'

  parseEmoji: true

update:
  method: never

# See https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md#custom-pull-request-urls
services: {}

# Keybindings
keybinding:
  universal:
    quit: q
    quit-alt1: <c-c>
    suspendApp: <disabled>
    return: <esc>
    quitWithoutChangingDirectory: Q
    togglePanel: <disabled>
    prevItem: <up>
    nextItem: <down>
    prevItem-alt: <disabled>
    nextItem-alt: <disabled>
    prevPage: <left>
    nextPage: <right>
    scrollLeft: '<'
    scrollRight: '>'
    gotoTop: <home>
    gotoBottom: <end>
    gotoTop-alt: <disabled>
    gotoBottom-alt: <disabled>
    toggleRangeSelect: v
    rangeSelectDown: <s-down>
    rangeSelectUp: <s-up>
    prevBlock: '('
    nextBlock: ')'
    prevBlock-alt: <disabled>
    nextBlock-alt: <disabled>
    prevBlock-alt2: <disabled>
    nextBlock-alt2: <disabled>
    jumpToBlock:
      - '1'
      - '4'
      - '5'
      - '6'
      - '2'
    focusMainView: <backtab>
    nextMatch: 'n'
    prevMatch: 'N'
    startSearch: /
    optionMenu: <disabled>
    optionMenu-alt1: '?'
    select: <tab>
    goInto: '.'
    confirm: <enter>
    confirmMenu: <enter>
    confirmSuggestion: <enter>
    confirmInEditor: <a-enter>
    confirmInEditor-alt: <c-s>
    remove: d
    new: 'n'
    edit: e
    openFile: o
    scrollUpMain: <pgup>
    scrollDownMain: <pgdown>
    scrollUpMain-alt1: <disabled>
    scrollDownMain-alt1: <disabled>
    scrollUpMain-alt2: <disabled>
    scrollDownMain-alt2: <disabled>
    executeShellCommand: ':'
    createRebaseOptionsMenu: m
    pushFiles: p
    pullFiles: u
    refresh: R
    createPatchOptionsMenu: <c-p>
    nextTab: '}'
    prevTab: '{'
    nextScreenMode: +
    prevScreenMode: '-'
    undo: <c-z>
    redo: <c-y>
    filteringMenu: <c-s>
    diffingMenu: W
    diffingMenu-alt: <c-e>
    copyToClipboard: <c-o>
    openRecentRepos: <c-r>
    submitEditorText: <enter>
    extrasMenu: '@'
    toggleWhitespaceInDiffView: ';'
    increaseContextInDiffView: ']'
    decreaseContextInDiffView: '['
    increaseRenameSimilarityThreshold: ','
    decreaseRenameSimilarityThreshold: "'"
    openDiffTool: <c-t>
  status:
    checkForUpdate: u
    recentRepos: <enter>
    allBranchesLogGraph: a
  files:
    commitChanges: c
    commitChangesWithoutHook: w
    amendLastCommit: A
    commitChangesWithEditor: C
    findBaseCommitForFixup: <c-f>
    confirmDiscard: x
    ignoreFile: i
    refreshFiles: r
    stashAllChanges: s
    viewStashOptions: S
    toggleStagedAll: a
    viewResetOptions: D
    fetch: f
    toggleTreeView: '`'
    openMergeOptions: M
    openStatusFilter: <c-b>
    copyFileInfoToClipboard: 'y'
    collapseAll: '|'
    expandAll: '='
  branches:
    createPullRequest: o
    viewPullRequestOptions: O
    copyPullRequestURL: <c-y>
    checkoutBranchByName: c
    forceCheckoutBranch: F
    checkoutPreviousBranch: '-'
    rebaseBranch: r
    renameBranch: R
    mergeIntoCurrentBranch: M
    moveCommitsToNewBranch: 'N'
    viewGitFlowOptions: i
    fastForward: f
    createTag: T
    pushTag: P
    setUpstream: U
    fetchRemote: f
    sortOrder: s
  worktrees:
    viewWorktreeOptions: w
  commits:
    squashDown: s
    renameCommit: r
    renameCommitWithEditor: R
    viewResetOptions: g
    markCommitAsFixup: f
    createFixupCommit: F
    squashAboveCommits: S
    moveDownCommit: D
    moveUpCommit: U
    amendToCommit: A
    resetCommitAuthor: a
    pickCommit: p
    revertCommit: t
    cherryPickCopy: C
    pasteCommits: V
    markCommitAsBaseForRebase: B
    tagCommit: T
    checkoutCommit: <tab>
    resetCherryPick: <c-R>
    copyCommitAttributeToClipboard: 'y'
    openLogMenu: <c-l>
    openInBrowser: o
    viewBisectOptions: b
    startInteractiveRebase: i
    selectCommitsOfCurrentBranch: '*'
  amendAttribute:
    resetAuthor: a
    setAuthor: A
    addCoAuthor: c
  stash:
    popStash: g
    renameStash: r
  commitFiles:
    checkoutCommitFile: c
  main:
    toggleSelectHunk: a
    pickBothHunks: b
    editSelectHunk: E
  submodules:
    init: i
    update: u
    bulkMenu: b
  commitMessage:
    commitMenu: <c-o>
